name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Lint, Format, Compile and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        id: setup-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Install Dependencies & Build
        id: cargo-build
        run: cargo build --workspace --all-targets

      - name: Check Format
        id: cargo-format-check
        run: cargo fmt -- --check

      - name: Lint
        id: cargo-lint
        run: cargo clippy -- -D warnings

      - name: Test
        id: cargo-test
        run: cargo test --workspace --all-targets
